sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: M1zQiz+AsNQi/JdwskuPepA8LJZunRufZg/wBlf35+2T5OohMqJ/7z5oH31S8nAJ8BvX5tb1kKJl505pakjd3DODcKcWC5MXuUSJn2Jt3P0H+TAX6N9lwSghbF94OtF1BJvUYZ+2CM9+b201GvGuxslGsH8uelCCHz2mFLnlFA3V1LJSnUhtLFdCkSky9Fn4v64Y6/+fOYZhExTjZClsFYIgAgRf2tPi49sHR10kmfmQldc3xDe4p4Yvd/0Oz7V1OqrgOUR9aGi5p3sZufQbVYXjeZYlkFmzonQLxuqd3XDRnPYmAqMP3tyYGagra6pZADqaI2VGcqb800N1htCvDAxeKI83w723Jldi/fleH72nxxMRbyaH4U3PmjwH3g6RW24cv91e1/ILvUDseFtAz/EK00rHlBbn3Q+Ijh+0/h1TddS63oGWZ5KYIQ1ianzKL6Y3khsHqohEZjWNtCnkALP9n07bbT4d4sVlGR5MFG4ZZskKq0cCUSJUkkiuRmr6BFjvw+g9H8zP8yW3ygw01KYxoY+4iQSdWVb+7OJPCLCmWBcmCilXhBlfD/A5f9hQy2D7qnZM+KeLS6oJyn/2hY8RnJ952/Eic8UNJ27mV/67/OMiPs8CuT29eXbAoNA+b6dq5IQXvj5j3Dsv0jvQNPtNIV0g26BTUCXVjEUAlxY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Thorny-Path-Volume-03_5532
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy